### ISSUE TITLE
请教这句话的出处

### ISSUE THREAD

**Issue by oikomi** [codeskyblue/minicdn#2]
MiniCDN使用了谷歌开源出来的groupcache框架，目前dl.google.com后台就用到了groupcache，性能而言远超那些squid或者nginx-proxy-cache.

这个性能对比有报告吗？

谢谢

**Comment by codeskyblue** [comment]
尚无。这个也只是理论上的，等下我修改下README。因为groupcache支持节点间的数据传输，而类似squid只能从源站点去获取数据，对原站点的压力较大。
